name: flutter_tizen
description: Flutter application build tools for Tizen devices
homepage: https://github.com/flutter-tizen/flutter-tizen
# Keep in sync with the base SDK version.
version: 1.22.12-pre.1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Keep in sync with the package versions in `flutter_tools/pubspec.yaml`.
dependencies:
  flutter_tools:
    path: flutter/packages/flutter_tools
  file: ^6.0.0-nullsafety.1
  meta: ^1.3.0-nullsafety.2
  package_config: ^1.9.3
  path: ^1.8.0-nullsafety
  process: ^4.0.0-nullsafety.1
  xml: ^4.4.1
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
